FROM python:3.6
EXPOSE 8501
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN pip3 install -r requirements.txt
RUN apt-get upgrade
RUN apt-get install libsm6 libxext6  -y
RUN pip install opencv-python-headless
COPY . .
CMD streamlit run demo/app.py